name: student_phonebook_android
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  # ပုံများနှင့် ဂျေဆန်ဖိုင်များ ထည့်ထားသော ဖိုင်တွဲလမ်းကြောင်းများ
  assets:
    - assets/
    - assets/images/

# App Launcher Icon Configuration (app_log.png ကို အသုံးပြုရန်)
flutter_launcher_icons:
  image_path: "assets/images/app_log.png"
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/app_log.png"